import Head from 'next/head';
import Image from 'next/image';
import Hero from '../../components/hero';
import Projects from '../../components/projects';
import Title from '../../components/title';
import About from '../../components/about';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
      </Head>
      <main className="main">
        <nav className="navbar">
          <ul className='navbar-link'>
            <li><Image src="/logo.svg" width={40} height={40}/></li>
            <li>&lt;Projects/&gt;</li>
            <li><Link href="#about">&lt;About Me/&gt;</Link></li>
            <li>&lt;Contact/&gt;</li>
          </ul>
        </nav>
        <div className='w-full h-[calc(100vh-3rem)] overflow-y-scroll'>
            <Hero/>
            <Title title="Projects"/>
            <Projects/>
            <Title title="About me"/>
            <About />
        </div>
      </main>
    </>
  )
}
